---
- name: install docker and docker compose
  hosts: all
  become: yes
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - python3-pip
        state: present

    - name: create docker key file directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: install docker key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: install repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: update cache again after adding Docker repo
      apt:
        update_cache: yes

    - name: List available Docker packages
      apt:
        name: docker-ce
        state: latest

    - name: install docker compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-{{ lookup('pipe', 'uname -s') }}-{{ lookup('pipe', 'uname -m') }}"
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Install specific version of Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose

- name: start docker service
  hosts: all
  become: yes
  tasks:
    - name: start docker
      systemd_service:
        name: docker
        state: started
        enabled: true

- name: add ubuntu user to docker group
  hosts: all
  become: yes
  tasks:
    - name: add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: reconnect to server
      meta: reset_connection

- name: run test docker image
  hosts: all
  become: yes
  tasks:
    - name: include variable files
      include_vars: vars/project-vars

    - name: pull redis docker image
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: docker login
      docker_login:
        registry_url: https://registry-1.docker.io/v2/
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: start docker-compose file
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
