variable "vpc_cidr_block" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_cidr_blocks" {}
variable "private_cidr_blocks" {}
variable "availability_zone_1" {}
variable "availability_zone_2" {}
variable "availability_zone_3" {}
variable "public_key_location" {}